version: '3'

services:

  nginx:
    build: ./containers/nginx
    ports:
      - 8080:80
    volumes:
      - ./:${APP_PATH_CONTAINER}
#      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
    working_dir: ${APP_PATH_CONTAINER}
